export var movies_all = [
'12 Angry Men',
'2001: A Space Odyssey',
'3 Idiots'
,"A Beautiful Mind"
,"A Clockwork Orange"
,"A Streetcar Named Desire"
,"Alien"
,"All About Eve"
,"All Quiet on the Western Front"
,"Amadeus"
,"American Beauty"
,"American History X"
,"Amores perros"
,"Anatomy of a Murder"
,"Annie Hall"
,"Apocalypse Now"
,"Arsenic and Old Lace"
,"Back to the Future"
,"Barry Lyndon"
,"Batman Begins"
,"Beauty and the Beast"
,"Before Sunrise"
,"Ben-Hur"
,"Black Swan"
,"Blade Runner"
,"Braveheart"
,"Butch Cassidy and the Sundance Kid"
,"Casablanca"
,"Casino"
,"Chinatown"
,"Cidade de Deus"
,"Citizen Kane"
,"City Lights"
,"Cool Hand Luke"
,"Die Hard"
,"District 9"
,"Django Unchained"
,"Dog Day Afternoon"
,"Donnie Darko"
,"Double Indemnity"
,"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb"
,"El laberinto del fauno"
,"Eternal Sunshine of the Spotless Mind"
,"Fanny och Alexander"
,"Fargo"
,"Festen"
,"Fight Club"
,"Finding Nemo"
,"Forrest Gump"
,"Full Metal Jacket"
,"Gandhi"
,"Gladiator"
,"Gone with the Wind"
,"Good Will Hunting"
,"Goodfellas"
,"Gran Torino"
,"Groundhog Day"
,"Harry Potter and the Deathly Hallows: Part 2"
,"Harvey"
,"Heat"
,"High Noon"
,"Hotel Rwanda"
,"How to Train Your Dragon"
,"Il buono"
,"In the Name of the Father"
,"Incendies"
,"Inception"
,"Indiana Jones and the Last Crusade"
,"Infernal Affairs"
,"Inglourious Basterds"
,"Into the Wild"
,"Intouchables"
,"It Happened One Night"
,"It's a Wonderful Life"
,"Jagten"
,"Jaws"
,"Jurassic Park"
,"Kaze no tani no Naushika"
,"Kill Bill: Vol. 1"
,"L.A. Confidential"
,"Lawrence of Arabia"
,"Life of Pi"
,"Lock"
,"M"
,"Mary and Max"
,"Memento"
,"Metropolis"
,"Million Dollar Baby"
,"Modern Times"
,"Mononoke-hime"
,"Monsters"
,"Monty Python and the Holy Grail"
,"Monty Python's Life of Brian"
,"Mr. Smith Goes to Washington"
,"Mystic River"
,"Network"
,"No Country for Old Men"
,"North by Northwest"
,"Notorious"
,"Nuovo Cinema Paradiso"
,"On the Waterfront"
,"Once Upon a Time in America"
,"One Flew Over the Cuckoo's Nest"
,"Papillon"
,"Paths of Glory"
,"Per un pugno di dollari"
,"Persona"
,"Pirates of the Caribbean: The Curse of the Black Pearl"
,"Platoon"
,"Psycho"
,"Pulp Fiction"
,"Raging Bull"
,"Raiders of the Lost Ark"
,"Rain Man"
,"Ran"
,"Ratatouille"
,"Rear Window"
,"Rebecca"
,"Requiem for a Dream"
,"Reservoir Dogs"
,"Rocky"
,"Roman Holiday"
,"Rope"
,"Rosemary's Baby"
,"Saving Private Ryan"
,"Scarface"
,"Schindler's List"
,"Se7en"
,"Shutter Island"
,"Sin City"
,"Singin' in the Rain"
,"Sleuth"
,"Slumdog Millionaire"
,"Snatch"
,"Some Like It Hot"
,"Stand by Me"
,"Star Trek"
,"Star Wars: Episode VI - Return of the Jedi"
,"Strangers on a Train"
,"Sunset Boulevard"
,"Taare Zameen Par"
,"Taxi Driver"
,"Terminator 2: Judgment Day"
,"The Apartment"
,"The Artist"
,"The Avengers"
,"The Best Years of Our Lives"
,"The Big Lebowski"
,"The Big Sleep"
,"The Bourne Ultimatum"
,"The Bridge on the River Kwai"
,"The Dark Knight"
,"The Deer Hunter"
,"The Departed"
,"The Elephant Man"
,"The Exorcist"
,"The General"
,"The Godfather"
,"The Gold Rush"
,"The Graduate"
,"The Grapes of Wrath"
,"The Great Dictator"
,"The Great Escape"
,"The Green Mile"
,"The Hobbit: An Unexpected Journey"
,"The Hustler"
,"The Kid"
,"The Killing"
,"The King's Speech"
,"The Lion King"
,"The Lord of the Rings: The Two Towers"
,"The Maltese Falcon"
,"The Man Who Shot Liberty Valance"
,"The Manchurian Candidate"
,"The Matrix"
,"The Night of the Hunter"
,"The Pianist"
,"The Prestige"
,"The Princess Bride"
,"The Shawshank Redemption"
,"The Shining"
,"The Silence of the Lambs"
,"The Sixth Sense"
,"The Sting"
,"The Terminator"
,"The Thing"
,"The Third Man"
,"The Treasure of the Sierra Madre"
,"The Truman Show"
,"The Untouchables"
,"The Usual Suspects"
,"The Wild Bunch"
,"The Wizard of Oz"
,"There Will Be Blood"
,"To Kill a Mockingbird"
,"Tonari no Totoro"
,"Touch of Evil"
,"Toy Story"
,"Trainspotting"
,"Trois couleurs: Rouge"]